### ISSUE TITLE
Typing "bottom" in expressions

### ISSUE THREAD

**Issue by jonasschneider** [nomeata/incredible#36]
Without having much of a clue about formal systems: is it intended that you can't type in "bottom" in the fill-in fields? Or is that just an oversight?

**Comment by nomeata** [comment]
You can write `False`, but it is not documented yet, and I hope that we have a good idea for a good ASCII representation for it.

**Comment by nomeata** [comment]
Also discussed on https://www.reddit.com/r/haskell/comments/3m7li1/the_incredible_proof_machine/cveheqx?context=3

`_|_` looks good in principle, but I could imagine to use `_` for holes in helper blocks (so that you can write `_ → _` if you just want to fix the outermost symbol), and then it would be ambiguous.
